services:
  - type: web
    name: qcloudcaptcha
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: hypercorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
